// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJTV0m0SIGKji_zFpCrIpViwtvv34K9E',
    appId: '1:711022851722:android:72e4feca9f535a9f739f73',
    messagingSenderId: '711022851722',
    projectId: 'rentalhouse-51d20',
    databaseURL: 'https://rentalhouse-51d20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rentalhouse-51d20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UarXfo7LRvxG5wWoBl1JFLrpf431Cho',
    appId: '1:711022851722:ios:de79085f410a7f4b739f73',
    messagingSenderId: '711022851722',
    projectId: 'rentalhouse-51d20',
    databaseURL: 'https://rentalhouse-51d20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rentalhouse-51d20.appspot.com',
    iosClientId: '711022851722-fvcm6ga9q69snk44a8ni8pt6h0kg8qg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.batruHouseRental',
  );
}
